// Network-level blocking, and the per-site exceptions to it.
//
// The block rules themselves are static (rules/ads.json, generated by
// scripts/build-rules.mjs) and ship with the extension. This file owns only the
// dynamic half: turning the user's allowlist into rules that let a site through.
//
// Why `allowAllRequests` rather than `allow`:
//   `allow` exempts a single request. What "turn it off for this site" means is
//   that nothing on the page is touched, including the hundred subresources it
//   pulls in. `allowAllRequests` on the document request does exactly that — it
//   exempts the frame and everything under it.
//
// Priority matters as much as the action. Static block rules sit at priority 1;
// these sit far above so an exception always wins.

const ALLOW_PRIORITY = 100

/**
 * Dynamic rule IDs live in their own range.
 *
 * Static and dynamic rules share an ID space, and colliding with a static rule
 * is the kind of mistake that shows up as "blocking randomly stopped working".
 * The static ruleset numbers from 1, so starting well past its ceiling keeps the
 * two apart no matter how the generated file grows.
 */
const DYNAMIC_ID_BASE = 1_000_000

/** Chrome caps how many domains one rule may carry; batching stays well under it. */
const BATCH_SIZE = 500

function batch<T>(items: T[], size: number): T[][] {
  const out: T[][] = []
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size))
  return out
}

/**
 * Two rules per batch, because one is not enough on its own.
 *
 *   allowAllRequests  matches the *document* request and exempts everything
 *                     beneath that frame. This is what "turn it off here" means,
 *                     but it only takes effect through the frame hierarchy.
 *   allow             matches by initiator, exempting requests the page sends
 *                     regardless of how the frame tree is walked.
 *
 * The overlap is deliberate. An exception that half-applies is worse than none:
 * the user switches a site off, sees it still broken, and concludes the switch
 * does nothing.
 */
function allowRulesFor(allowlist: readonly string[]): chrome.declarativeNetRequest.Rule[] {
  const hosts = [...new Set(allowlist.map((h) => h.trim().toLowerCase()).filter(Boolean))]
  if (!hosts.length) return []

  const rules: chrome.declarativeNetRequest.Rule[] = []
  let id = DYNAMIC_ID_BASE

  for (const domains of batch(hosts, BATCH_SIZE)) {
    rules.push({
      id: id++,
      priority: ALLOW_PRIORITY,
      action: { type: 'allowAllRequests' as chrome.declarativeNetRequest.RuleActionType },
      condition: {
        requestDomains: domains,
        resourceTypes: [
          'main_frame',
          'sub_frame',
        ] as chrome.declarativeNetRequest.ResourceType[],
      },
    })
    rules.push({
      id: id++,
      priority: ALLOW_PRIORITY,
      action: { type: 'allow' as chrome.declarativeNetRequest.RuleActionType },
      condition: { initiatorDomains: domains },
    })
  }

  return rules
}

/**
 * Make the dynamic rules match the allowlist exactly.
 *
 * Every one of ours is removed and rewritten rather than diffed. The set is
 * tiny, and a diff that drifts leaves a site permanently exempt — a failure the
 * user would experience as "ads came back on that one site" and never report.
 */
export async function syncAllowlistRules(allowlist: readonly string[]): Promise<void> {
  try {
    const existing = await chrome.declarativeNetRequest.getDynamicRules()
    const removeRuleIds = existing.filter((r) => r.id >= DYNAMIC_ID_BASE).map((r) => r.id)

    await chrome.declarativeNetRequest.updateDynamicRules({
      removeRuleIds,
      addRules: allowRulesFor(allowlist),
    })
  } catch (e) {
    // Losing the exceptions means over-blocking, not under-blocking, so this is
    // not worth failing the worker over — but it must be visible.
    console.warn('[oc-ad-bye-pass] failed to sync allowlist rules', e)
  }
}
